Nhom4_DoAnWeb_CHDT/Controllers/NhanVienController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class NhanVienController : Controller
    {
        // GET: NhanVien
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult danh_sach()
        {
            var all_NV = from nv in data.tblNHANVIENs select nv;
            return View(all_NV);
        }
        //Get: NhanVien/Search
        public ActionResult tim_kiem(string searchName)
        {
            var search = data.tblNHANVIENs.Where(p => p.TENNV.ToLower().Contains(searchName.ToLower()));
            return View(search);
        }
        // GET: NhanVien/Details/5
        public ActionResult thong_tin(int id)
        {
            var D_nv = data.tblNHANVIENs.First(p => p.MANV == id);
            if(D_nv != null)
                return View(D_nv);
            return View("danh_sach");
        }

        // GET: NhanVien/Create
        public ActionResult them_moi()
        {
            return View();
        }

        // POST: NhanVien/Create
        [HttpPost]
        public ActionResult them_moi(FormCollection collection, tblNHANVIEN nv)
        {
            try
            {
                // TODO: Add insert logic here
                var C_tenNV = collection["TENNV"];
                var C_diachi = collection["DIACHI"];
                var C_dienthoai = collection["DIENTHOAI"];
                var C_email = collection["EMAIL"];
                var check = data.tblNHANVIENs.FirstOrDefault(p => p.EMAIL == C_email);
                if (check != null)
                {
                    ViewData["emailTonTai"] = "Email đã tồn tại!";
                    return this.them_moi();
                }
                if (!Regex.IsMatch(C_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.them_moi();
                }
                if (!Regex.IsMatch(C_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.them_moi();
                }
                if (string.IsNullOrEmpty(C_tenNV) || string.IsNullOrEmpty(C_diachi)
                    || string.IsNullOrEmpty(C_dienthoai) || string.IsNullOrEmpty(C_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.them_moi();
                }
                else
                {
                    nv.TENNV = C_tenNV;
                    nv.DIACHI = C_diachi;
                    nv.DIENTHOAI = C_dienthoai;
                    nv.EMAIL = C_email;

                    data.tblNHANVIENs.InsertOnSubmit(nv);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
                return this.them_moi();
            }
            catch
            {
                return View();
            }
        }

        // GET: NhanVien/Edit/5
        public ActionResult sua_thong_tin(int? id)
        {
            var E_nv = data.tblNHANVIENs.First(p => p.MANV == id);
            if (E_nv != null)
                return View(E_nv);
            return View("danh_sach");
        }

        // POST: NhanVien/Edit/5
        [HttpPost]
        public ActionResult sua_thong_tin(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                var E_tenNV = collection["TENNV"];
                var E_diachi = collection["DIACHI"];
                var E_dienthoai = collection["DIENTHOAI"];
                var E_email = collection["EMAIL"];
                var nv = data.tblNHANVIENs.First(p => p.MANV == id);
                if (!Regex.IsMatch(E_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.sua_thong_tin(id);
                }
                if (!Regex.IsMatch(E_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.sua_thong_tin(id);
                }
                if (string.IsNullOrEmpty(E_tenNV) || string.IsNullOrEmpty(E_diachi)
                    || string.IsNullOrEmpty(E_dienthoai) || string.IsNullOrEmpty(E_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                }
                else
                {
                    nv.TENNV = E_tenNV;
                    nv.DIACHI = E_diachi;
                    nv.DIENTHOAI = E_dienthoai;
                    nv.EMAIL = E_email;

                    UpdateModel(nv);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
                return this.sua_thong_tin(id);
            }
            catch
            {
                return View();
            }
        }

        // GET: NhanVien/Delete/5
        public ActionResult xoa_nhan_vien(int? id)
        {
            var D_nv = data.tblNHANVIENs.First(p => p.MANV == id);
            if (D_nv != null)
                return View(D_nv);
            return View("danh_sach");
        }

        // POST: NhanVien/Delete/5
        [HttpPost]
        public ActionResult xoa_nhan_vien(int id, FormCollection collection)
        {
            var delNV = data.tblNHANVIENs.First(p => p.MANV == id);
            data.tblNHANVIENs.DeleteOnSubmit(delNV);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
    }
}

Nhom4_DoAnWeb_CHDT/Views/NhanVien/danh_sach.cshtml
@model IEnumerable<Nhom4_DoAnWeb_CHDT.Models.tblNHANVIEN>
@{
    ViewBag.Title = "Nhân Viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh Sách Nhân Viên</h2>
<p>
    @Html.ActionLink("Thêm Nhân Viên mới", "them_moi", null, new { @class = "btn btn-warning" })
</p>
@using (Html.BeginForm("tim_kiem", "NhanVien", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 " name="searchName" placeholder="Nhập tên Nhân Viên cần tìm">
        <input type="submit" value="Search" class="btn btn-info" />
    </p>
}
<table border="1px">
    <tr>
        <th width="130" style="text-align:center">Mã Nhân Viên</th>
        <th width="150" style="text-align:center">Tên Nhân Viên</th>
        <th width="230" style="text-align:center">Địa chỉ</th>
        <th width="100" style="text-align:center">Điện Thoại</th>
        <th width="190" style="text-align:center">Email</th>
        <th width="160" style="text-align:center">Công cụ</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MANV</td>
            <td style="text-align:center">@item.TENNV</td>
            <td style="text-align:center">@item.DIACHI</td>
            <td style="text-align:center">@item.DIENTHOAI</td>
            <td style="text-align:center">@item.EMAIL</td>
            <td style="text-align:center; font-size:20px">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MANV })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="18px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MANV })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="22px" />
                </a> |
                <a href="@Url.Action("xoa_nhan_vien", new { id = item.MANV })" title="Delete">
                    <img src="~/Content/images/delete-icon.png" alt="Edit" width="19px" />
                </a>
            </td>
        </tr>
    }
</table>
<br />
<p  style="color:white;">
    @Html.ActionLink("Tạo tài khoản mới nhân viên", "DangKy_NV", "NguoiDung", null, new { @class = "btn btn-success" })
</p>

<style>
    a:hover img {
        position: relative;
        top: -3px;
    }

    img {
        vertical-align: text-bottom;
    }
</style>

Nhom4_DoAnWeb_CHDT/Views/NhanVien/sua_thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHANVIEN

@{
    ViewBag.Title = "Sửa thông tin nhân viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin Nhân Viên</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MANV)
        <span style="color:red">@ViewData["Error"]</span>
        <div class="form-group">
            <p class="control-label col-md-2">Tên Nhân Viên: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TENNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TENNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Địa chỉ: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Điện thoại: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIENTHOAI, "", new { @class = "text-danger" })
            </div>
            <span style="color:red">@ViewData["SDTKhongHopLe"]</span>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Email: </p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
            <span style="color:red">@ViewData["EmailKhongHopLe"]</span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT/Views/NhanVien/them_moi.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHANVIEN

@{
    ViewBag.Title = "Thêm mới nhân viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thêm Nhân Viên</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <fieldset>
            <span style="color:red">@ViewData["Error"]</span>
            <div class="form-group">
                <label class="control-label col-md-2" for="TENNV">Tên Nhân Viên:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="TENNV" name="TENNV" value="@ViewBag.TENNV" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="DIACHI">Địa chỉ:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="DIACHI" name="DIACHI" value="@ViewBag.DIACHI" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="DIENTHOAI">Điện thoại:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="DIENTHOAI" name="DIENTHOAI" value="@ViewBag.DIENTHOAI" />
                </div>
                <span style="color:red">@ViewData["SDTKhongHopLe"]</span>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="EMAIL">Email:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="EMAIL" name="EMAIL" value="@ViewBag.EMAIL" />
                </div>
                <span style="color:red">@ViewData["emailTonTai"]</span>
                <span style="color:red">@ViewData["EmailKhongHopLe"]</span>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm mới" class="btn btn-default" />
                </div>
            </div>
        </fieldset>
    </div>
}
<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT/Views/NhanVien/thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHANVIEN

@{
    ViewBag.Title = "Thông tin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin Nhân Viên</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Nhân Viên:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNV)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            Điện Thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIENTHOAI)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "sua_thong_tin", new { id = Model.MANV }) |
    @Html.ActionLink("Quay lại", "danh_sach")
</p>

Nhom4_DoAnWeb_CHDT/Views/NhanVien/tim_kiem.cshtml
@model IEnumerable<Nhom4_DoAnWeb_CHDT.Models.tblNHANVIEN>
@{
    ViewBag.Title = "Tìm kiếm nhân viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Nhân Viên cần tìm</h2>
@using (Html.BeginForm("tim_kiem", "NhanVien", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 " name="searchName" placeholder="Nhập tên Nhân Viên cần tìm">
        <input type="submit" value="Tìm kiếm" class="btn btn-info" />
    </p>
}
<table border="1px">
    <tr>
        <th width="130" style="text-align:center">Mã Nhân Viên</th>
        <th width="150" style="text-align:center">Tên Nhân Viên</th>
        <th width="230" style="text-align:center">Địa chỉ</th>
        <th width="100" style="text-align:center">Điện Thoại</th>
        <th width="190" style="text-align:center">Email</th>
        <th width="160"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MANV</td>
            <td style="text-align:center">@item.TENNV</td>
            <td style="text-align:center">@item.DIACHI</td>
            <td style="text-align:center">@item.DIENTHOAI</td>
            <td style="text-align:center">@item.EMAIL</td>
            <td style="text-align:center">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MANV })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="20px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MANV })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="24px" />
                </a> |
                <a href="@Url.Action("xoa_nhan_vien", new { id = item.MANV })" title="Delete">
                    <img src="~/Content/images/delete-icon.png" alt="Edit" width="21px" />
                </a>
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Quay lại", "danh_sach")

Nhom4_DoAnWeb_CHDT/Views/NhanVien/xoa_nhan_vien.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHANVIEN

@{
    ViewBag.Title = "Xóa nhân viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Xóa Nhân Viên</h2>

<h3>Chắc chắn muốn xóa Nhân Viên này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Nhân Viên:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNV)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            Điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIENTHOAI)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "danh_sach")
        </div>
    }
</div>