Nhom4_DoAnWeb_CHDT/Controllers/NCCController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class NCCController : Controller
    {
        // GET: NCC
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult danh_sach()
        {
            var all_NCC = from ncc in data.tblNHACUNGCAPs select ncc;
            return View(all_NCC);
        }
        //Get: LoaiDT/Search
        public ActionResult tim_kiem(string searchName)
        {
            var search = data.tblNHACUNGCAPs.Where(p => p.TENNCC.ToLower().Contains(searchName.ToLower()));
            return View(search);
        }
        // GET: NCC/Details/5
        public ActionResult thong_tin(int id)
        {
            var D_nhacungcap = data.tblNHACUNGCAPs.First(m => m.MANCC == id);
            if(D_nhacungcap != null)
                return View(D_nhacungcap);
            return View("danh_sach");
        }
        // GET: NCC/Create
        public ActionResult them_moi()
        {
            return View();
        }
        
        // POST: NCC/Create
        [HttpPost]
        public ActionResult them_moi(FormCollection collection, tblNHACUNGCAP ncc)
        {
            try
            {
                var C_tenNCC = collection["TENNCC"];
                var C_diachi = collection["DIACHI"];
                var C_dienthoai = collection["DIENTHOAI"];
                var C_email = collection["EMAIL"];
                if (!Regex.IsMatch(C_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.them_moi();
                }
                if (!Regex.IsMatch(C_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.them_moi();
                }
                if (string.IsNullOrEmpty(C_tenNCC) || string.IsNullOrEmpty(C_diachi)
                    || string.IsNullOrEmpty(C_dienthoai) || string.IsNullOrEmpty(C_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.them_moi();
                }
                else
                {
                    ncc.TENNCC = C_tenNCC;
                    ncc.DIACHI = C_diachi;
                    ncc.DIENTHOAI = C_dienthoai;
                    ncc.EMAIL = C_email;

                    data.tblNHACUNGCAPs.InsertOnSubmit(ncc);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: NCC/Edit/5
        public ActionResult sua_thong_tin(int? id)
        {
            var ncc = data.tblNHACUNGCAPs.First(m => m.MANCC == id);
            if(ncc != null)
                return View(ncc);
            return View("danh_sach");
        }

        // POST: NCC/Edit/5
        [HttpPost]
        public ActionResult sua_thong_tin(int id, FormCollection collection)
        {
            try
            {
                var ncc = data.tblNHACUNGCAPs.First(p => p.MANCC == id);
                var E_tenncc = collection["TENNCC"];
                var E_diachi = collection["DIACHI"];
                var E_dienthoai = collection["DIENTHOAI"];
                var E_email = collection["EMAIL"];
                if (!Regex.IsMatch(E_dienthoai, "^0\\d{9}$"))
                {
                    ViewData["SDTKhongHopLe"] = "Số điện thoại không hợp lệ!";
                    return this.them_moi();
                }
                if (!Regex.IsMatch(E_email, @"^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"))
                {
                    ViewData["EmailKhongHopLe"] = "Địa chỉ email không hợp lệ!";
                    return this.them_moi();
                }
                if (string.IsNullOrEmpty(E_tenncc) || string.IsNullOrEmpty(E_diachi)
                    || string.IsNullOrEmpty(E_dienthoai) || string.IsNullOrEmpty(E_email))
                {
                    ViewData["Error"] = "Vui lòng điền đầy đủ thông tin!";
                    return this.sua_thong_tin(id);
                }
                else
                {
                    ncc.TENNCC = E_tenncc;
                    ncc.DIACHI = E_diachi;
                    ncc.DIENTHOAI = E_dienthoai;
                    ncc.EMAIL = E_email;

                    UpdateModel(ncc);
                    data.SubmitChanges();
                    return RedirectToAction("danh_sach");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: NCC/Delete/5
        public ActionResult xoa_NCC(int? id)
        {
            var search = data.tblNHACUNGCAPs.First(p => p.MANCC == id);
            if (search != null)
                return View(search);
            return View("danh_sach");
        }

        // POST: NCC/Delete/5
        [HttpPost]
        public ActionResult xoa_NCC(int id, FormCollection collection)
        {
            var delNCC = data.tblNHACUNGCAPs.First(p => p.MANCC == id);
            data.tblNHACUNGCAPs.DeleteOnSubmit(delNCC);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
    }
}

Nhom4_DoAnWeb_CHDT/Views/NCC/danh_sach.cshtml
@model IEnumerable<Nhom4_DoAnWeb_CHDT.Models.tblNHACUNGCAP>
@{
    ViewBag.Title = "Nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh Sách Nhà Cung Cấp</h2>
<p>
    @Html.ActionLink("Thêm Nhà Cung Cấp mới", "them_moi", null, new { @class = "btn btn-warning" })
</p>
@using (Html.BeginForm("tim_kiem", "NCC", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 " name="searchName" placeholder="Nhập tên Nhà Cung Cấp cần tìm">
        <input type="submit" value="Search" class="btn btn-info" />
    </p>
}
<table border="1px">
    <tr>
        <th width="130" style="text-align:center">Mã Nhà Cung Cấp</th>
        <th width="150" style="text-align:center">Tên Nhà Cung Cấp</th>
        <th width="230" style="text-align:center">Địa chỉ</th>
        <th width="100" style="text-align:center">Điện Thoại</th>
        <th width="190" style="text-align:center">Email</th>
        <th width="160"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr style="margin:10px 0">
            <td style="text-align:center">@item.MANCC</td>
            <td style="text-align:center">@item.TENNCC</td>
            <td style="text-align:center">@item.DIACHI</td>
            <td style="text-align:center">@item.DIENTHOAI</td>
            <td style="text-align:center">@item.EMAIL</td>
            <td style="text-align:center; font-size:20px">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MANCC })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="20px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MANCC })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="24px" />
                </a> |
                <a href="@Url.Action("xoa_NCC", new { id = item.MANCC })" title="Delete">
                    <img src="~/Content/images/delete-icon.png" alt="Edit" width="21px" />
                </a>
            </td>
        </tr>
    }
</table>
<style>
    a:hover img {
        position: relative;
        top: -3px;
    }

    img {
        vertical-align: text-bottom;
    }
</style>

Nhom4_DoAnWeb_CHDT/Views/NCC/sua_thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHACUNGCAP

@{
    ViewBag.Title = "Sửa thông tin Nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin Nhà Cung Cấp</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MANCC)
    <span style="color:red">@ViewData["Error"]</span>
    <div class="form-group">
        <p class="control-label col-md-2">Tên Nhà Cung Cấp:  </p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TENNCC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENNCC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p class="control-label col-md-2">Địa chỉ: </p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <p class="control-label col-md-2">Điện thoại: </p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DIENTHOAI, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DIENTHOAI, "", new { @class = "text-danger" })
        </div>
        <span style="color:red">@ViewData["SDTKhongHopLe"]</span>
    </div>

    <div class="form-group">
        <p class="control-label col-md-2">Email: </p>
        <div class="col-md-10">
            @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
        </div>
        <span style="color:red">@ViewData["EmailKhongHopLe"]</span>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT/Views/NCC/them_moi.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblLOAIDIENTHOAI

@{
    ViewBag.Title = "Thêm mới Nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thêm Nhà Cung Cấp</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <fieldset>
            <span style="color:red">@ViewData["Error"]</span>
            <div class="form-group">
                <label class="control-label col-md-2" for="TENNCC">Tên nhà cung cấp:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="TENNCC" name="TENNCC" value="@ViewBag.TENNCC" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="DIACHI">Địa chỉ:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="DIACHI" name="DIACHI" value="@ViewBag.DIACHI" />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="DIENTHOAI">Điện thoại:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="DIENTHOAI" name="DIENTHOAI" value="@ViewBag.DIENTHOAI" />
                </div>
                <span style="color:red">@ViewData["SDTKhongHopLe"]</span>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="EMAIL">Email:</label>
                <div class="col-md-10">
                    <input class="form-control" type="text" id="EMAIL" name="EMAIL" value="@ViewBag.EMAIL" />
                </div>
                <span style="color:red">@ViewData["EmailKhongHopLe"]</span>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm mới" class="btn btn-default" />
                </div>
            </div>
        </fieldset>
    </div>
}
<div>
    @Html.ActionLink("Quay lại", "danh_sach")
</div>

Nhom4_DoAnWeb_CHDT/Views/NCC/thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHACUNGCAP

@{
    ViewBag.Title = "Thông tin Nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin Nhà Cung Cấp</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Nhà Cung Cấp:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNCC)
        </dd>

        <dt>
            Địa chỉ:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            Điện Thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIENTHOAI)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Quay lại", "danh_sach") |
    @Html.ActionLink("Sửa Nhà cung cấp", "sua_thong_tin", new {id = Model.MANCC })
</p>

Nhom4_DoAnWeb_CHDT/Views/NCC/tim_kiem.cshtml
@model IEnumerable<Nhom4_DoAnWeb_CHDT.Models.tblNHACUNGCAP>
@{
    ViewBag.Title = "Tìm kiếm Nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Nhà Cung Cấp cần tìm</h2>
@using (Html.BeginForm("tim_kiem", "NCC", FormMethod.Get))
{
    <p>
        <input type="Text" class="form-control col-md-10 " name="searchName" placeholder="Nhập tên Nhà Cung Cấp cần tìm">
        <input type="submit" value="Tìm kiếm" class="btn btn-info" />
    </p>
}
<table border="1px">
    <tr>
        <th width="130" style="text-align:center">Mã Nhà Cung Cấp</th>
        <th width="150" style="text-align:center">Tên Nhà Cung Cấp</th>
        <th width="230" style="text-align:center">Địa chỉ</th>
        <th width="100" style="text-align:center">Điện Thoại</th>
        <th width="190" style="text-align:center">Email</th>
        <th width="160"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MANCC</td>
            <td style="text-align:center">@item.TENNCC</td>
            <td style="text-align:center">@item.DIACHI</td>
            <td style="text-align:center">@item.DIENTHOAI</td>
            <td style="text-align:center">@item.EMAIL</td>
            <td style="text-align:center">
                <a href="@Url.Action("sua_thong_tin", new { id = item.MANCC })" title="Edit">
                    <img src="~/Content/images/edit-icon.png" alt="Edit" width="20px" />
                </a> |
                <a href="@Url.Action("thong_tin", new { id = item.MANCC })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Edit" width="24px" />
                </a> |
                <a href="@Url.Action("xoa_NCC", new { id = item.MANCC })" title="Delete">
                    <img src="~/Content/images/delete-icon.png" alt="Edit" width="21px" />
                </a>
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Quay lại", "danh_sach")

Nhom4_DoAnWeb_CHDT/Views/NCC/xoa_NCC.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHACUNGCAP

@{
    ViewBag.Title = "Xóa Nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Xóa Nhà Cung Cấp</h2>

<h3>Chắc chắn muốn xóa Nhà Cung Cấp này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Nhà Cung Cấp: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENNCC)
        </dd>

        <dt>
            Địa chỉ: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            Điện thoại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIENTHOAI)
        </dd>

        <dt>
            Email:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
             @Html.ActionLink("Quay lại", "danh_sach") |
            <input style="margin-left:30px" type="submit" value="Xóa" class="btn btn-default" />
        </div>
    }
</div>