Nhom4_DoAnWeb_CHDT/Controllers/NhapKhoController.cs
using Nhom4_DoAnWeb_CHDT.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace Nhom4_DoAnWeb_CHDT.Controllers
{
    public class NhapKhoController : Controller
    {
        // GET: NhapKho
        MyDataDataContext data = new MyDataDataContext();

        public ActionResult danh_sach_NK(int? page)
        {
            var all_nk = (from s in data.tblNHAPKHOs select s).OrderBy(m => m.MAPNK);
            int pageSize = 12;
            int pageNum = page ?? 1;
            return View(all_nk.ToPagedList(pageNum, pageSize));
        }
        // GET: NhapKho/Details/5
        public ActionResult thong_tin(int id)
        {
            var find = data.tblNHAPKHOs.First(p => p.MAPNK == id);
            if (find != null)
            {
                var ctnk = data.tblCTPNHAPKHOs.Where(p => p.MAPNK == id).ToList();
                ViewBag.cthd = ctnk;
                return View(find);
            }
            return View("Index", "Home");
        }

        public ActionResult xoa_NK(int id)
        {
            var find = data.tblNHAPKHOs.FirstOrDefault(p => p.MAPNK == id);
            if (find != null)
                return View(find);
            return View("Index", "Home");
        }

        // POST: HoaDon/Delete/5
        [HttpPost]
        public ActionResult xoa_NK(int id, FormCollection collection)
        {
            var delNK = data.tblNHAPKHOs.FirstOrDefault(p => p.MAPNK == id);
            if (delNK != null)
            {
                var ctnk = data.tblCTPNHAPKHOs.Where(p => p.MAPNK == id).ToList();
                foreach (var item in ctnk)
                {
                    var dt = data.tblDIENTHOAIs.FirstOrDefault(p => p.MADT == item.MADT);
                    if (dt != null)
                    {
                        dt.SLTON -= item.SL;
                    }
                }
                ViewBag.ctnk = ctnk;
                data.tblCTPNHAPKHOs.DeleteAllOnSubmit(ctnk);
                data.SubmitChanges();
            }
            data.tblNHAPKHOs.DeleteOnSubmit(delNK);
            data.SubmitChanges();
            return RedirectToAction("danh_sach");
        }
    }
}

Nhom4_DoAnWeb_CHDT/Views/NhapKho/danh_sach_NK.cshtml
@model PagedList.IPagedList<Nhom4_DoAnWeb_CHDT.Models.tblNHAPKHO>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Nhập kho";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Danh sách các Phiếu nhập kho</h2>
<hr />
@using Nhom4_DoAnWeb_CHDT.Models
@{
    tblTAIKHOAN tk = (tblTAIKHOAN)Session["TaiKhoan"];
}
<table border="1px">
    <tr>
        <th width="100" style="text-align:center">Mã phiếu nhập kho</th>
        <th width="120" style="text-align:center">Ngày nhập</th>
        <th width="80" style="text-align:center">Tổng tiền</th>
        <th width="120" style="text-align:center">Mã nhà cung cấp</th>
        <th width="120" style="text-align:center">Mã nhân viên</th>
        <th width="180" style="text-align:center">Danh mục</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:center">@item.MAPNK</td>
            <td style="text-align:center">@item.NGAYNHAP</td>
            <td style="text-align:center">@item.TONGTG</td>
            <td style="text-align:center">@item.MANCC</td>
            <td style="text-align:center">@item.MANV</td>
            <td style="text-align:center; font-size:24px">
                <a href="@Url.Action("thong_tin", new { id = item.MAPNK })" title="Detail">
                    <img src="~/Content/images/detail-icon.png" alt="Detail" width="29px" />
                </a>
            </td>
        </tr>
    }
</table>
<div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) /  @Model.PageCount
    </div>
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("danh_sach_NK", "NhapKho", new
        {
            page = page
        }))
    </div>
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>
<style type="text/css">
    #mau-nut a {
        clear: both;
        background-color: orange;
        color: snow;
    }

        #mau-nut a:hover {
            background-color: darkcyan;
            color: snow;
        }
</style>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function () {
        var maxLength = 100;
        $(".show-read-more").each(function () {
            var myStr = $(this).text();
            if ($.trim(myStr).length > maxLength) {
                var newStr = myStr.substring(0, maxLength);
                var removedStr = myStr.substring(maxLength, $.trim(myStr).length);
                $(this).empty().html(newStr);

                $(this).append(' <a href="javascript:void(0);" class="read-more">đọc tiếp...</a>');

                $(this).append('<span class="more-text">' + removedStr + '</span>');
            }
        });
        $(".read-more").click(function () {
            $(this).siblings(".more-text").contents().unwrap();
            $(this).remove();
        });
    });
</script>
<style>
    .show-read-more .more-text {
        display: none;
    }
</style>

Nhom4_DoAnWeb_CHDT/Views/NhapKho/thong_tin.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHAPKHO
@{
    ViewBag.Title = "Thông tin nhập kho";
}

<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">Thông tin nhập kho</h2>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <p>Mã phiếu nhập kho: @Model.MAPNK</p>
                <p>Ngày nhập: @Model.NGAYNHAP</p>
                <p>Mã nhà cung cấp: @Model.MANCC</p>
                <p>Mã nhân viên: @Model.MANV</p>
                <p>Tổng tiền: @Model.TONGTG</p>
            </div>
            @if (ViewBag.ctnk != null && ViewBag.ctnk.Count > 0)
            {
                <div class="col-md-6">
                    <h3>Chi tiết phiếu nhập kho:</h3>
                    <table class="table table-bordered">
                        <tr>
                            <th scope="col" class="text-center">Mã điện thoại</th>
                            <th scope="col" class="text-center">Số lượng</th>
                            <th scope="col" class="text-center">Đơn giá</th>
                        </tr>
                        @foreach (var item in ViewBag.ctnk)
                        {
                            <tr>
                                <td class="text-center">@item.MADT</td>
                                <td class="text-center">@item.SL</td>
                                <td class="text-center">@item.GIANHAP</td>
                            </tr>
                        }
                    </table>
                </div>
            }
        </div>
    </div>
</div>
<br />
<div class="col-md-12">
    @Html.ActionLink("Quay lại", "danh_sach_NK", "NhapKho")
</div>

Nhom4_DoAnWeb_CHDT/Views/NhapKho/xoa_NK.cshtml
@model Nhom4_DoAnWeb_CHDT.Models.tblNHAPKHO
@{
    ViewBag.Title = "Xóa phiếu nhập kho";
}

<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">Xóa phiếu nhập kho</h2>
        <h3>Chắc chắn muốn xóa phiếu nhập kho này?</h3>
        <hr />
        <div class="row">
            <div class="col-md-6">
                <p>Mã hóa đơn: @Model.MAPNK</p>
                <p>Ngày lập: @Model.NGAYNHAP</p>
                <p>Mã khách hàng: @Model.MANCC</p>
                <p>Mã nhân viên: @Model.MANV</p>
                <p>Tổng tiền: @Model.TONGTG</p>
            </div>
            @if (ViewBag.ctnk != null && ViewBag.ctnk.Count > 0)
            {
                <div class="col-md-6">
                    <h3>Chi tiết phiếu nhập kho:</h3>
                    <table class="table table-bordered">
                        <tr>
                            <th scope="col" class="text-center">Mã điện thoại</th>
                            <th scope="col" class="text-center">Số lượng</th>
                            <th scope="col" class="text-center">Đơn giá</th>
                        </tr>
                        @foreach (var item in ViewBag.ctnk)
                        {
                            <tr>
                                <td class="text-center">@item.MADT</td>
                                <td class="text-center">@item.SL</td>
                                <td class="text-center">@item.GIANHAP</td>
                            </tr>
                        }
                    </table>
                </div>
            }
        </div>
    </div>
</div>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @Html.ActionLink("Quay lại", "danh_sach_NK", "NhapKho") |
        <input style="margin-left:30px" type="submit" value="Xóa" class="btn btn-default" />
    </div>
}